name: Deploy Website

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'  # Update to the required Node.js version

      - name: Change directory to client
        run: cd client

      - name: Install dependencies
        run: npm install
        working-directory: ./client  # Set working directory to client

      - name: Build the project
        run: npm run build
        working-directory: ./client  # Set working directory to client

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/out  # Ensure this matches your build output directory
